// libs/angular/ui-core/src/lib/alert/alert.component.ts
import { Component, OnInit, NgModule, Input, ViewEncapsulation, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IconComponentModule } from '../icon/icon.component';
const closeBtn = require('../../../../../../assets/close.svg');


@Component({
  selector: 'ng-ui-core-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class AlertComponent {

  @Input() title = 'Заголовок';
  @Input() subtitle = 'Подзаголовок';
  @Input() style? = {};
  @Input() type: 'info' | 'success' | 'warning' | 'error' = 'info';
  @Input() closable = true;
  @Input() onClose?: () => void;
  iconName = 'information';
  btnPath: any;
  visible = true;
  closing = '';

  constructor(private host: ElementRef<HTMLElement>) {
    this.btnPath = closeBtn;
  }

  getIconName() {
    if (this.type === 'info') return 'information';
    if (this.type === 'success') return 'checkbox-circle';
    if (this.type === 'warning') return 'error-warning';
    if (this.type === 'error') return 'close-circle';
    return '';
  }

  closeAlert() {
    this.closing = ' alert-closing';
    this.onClose?.();
    setTimeout(() => {
      this.host.nativeElement.remove();
    }, 150);
  }
}

@NgModule({
  imports: [CommonModule, IconComponentModule],
  declarations: [AlertComponent],
  exports: [AlertComponent],
})
export class AlertComponentModule {}


<div [ngClass]="'alert alert-'+type+closing" [style]="style" *ngIf="visible">
    <ng-ui-core-icon [name]="getIconName()" [size]="20" [class]="'alert-icon'" type="fill"></ng-ui-core-icon>
    <div class="alert-content">
        <div class="alert-header">
            {{title}}
        </div>
        <div class="alert-subtitle" *ngIf="subtitle">{{subtitle}}</div>
        <ng-content class="alert-children"></ng-content>
    </div>
    <div class="alert-close-icon-container" *ngIf="closable" (click)="closeAlert()">
        <img [src]="btnPath" alt="close" class="alert-close-icon">
    </div>
</div>

// libs/react/ui-core/src/lib/alert/alert.tsx
import { forwardRef } from 'react';
import Icon from '../icon/icon';
import styles from './alert.module.scss';
import { AlertProps } from './AlertProps';
import { useAlert } from './useAlert';
import { ReactComponent as CloseIcon } from '../../../../../../assets/close.svg';

export const Alert = forwardRef((props: AlertProps, ref?: any) => {
  const { classes, visible, iconName, closeAlert } = useAlert(props);

  return (
    <>
      {visible && (
        <div className={classes} style={props.style} ref={ref}>
          <Icon
            name={iconName}
            className={styles['alert-icon']}
            size={20}
            type="fill"
          />
          <div className={styles['alert-content']}>
            <div className={styles['alert-header']}>{props.title}</div>
            {props.subtitle && (
              <div className={styles['alert-subtitle']}>{props.subtitle}</div>
            )}
            {props.children && (
              <div className={styles['alert-children']}>{props.children}</div>
            )}
          </div>
          {props.closable && (
            <div
              className={styles['alert-close-icon-container']}
              onClick={closeAlert}
            >
              <CloseIcon className={styles['alert-close-icon']} />
            </div>
          )}
        </div>
      )}
    </>
  );
});

Alert.defaultProps = { type: 'info', closable: true };
